package com.FormDesigner.constants;

public enum EventType {
    USER, FORM, FIELD, ADMIN, TEMPLATE, THEME, DASHBOARD, REPORT, WIDGET,
    NOTIFICATION, INTEGRATION, AUTHENTICATION, AUTHORIZATION, LOGGING, AUDIT, BACKUP, RESTORE,
    API, WEBHOOK, SSO, MFA, PASSWORD, SESSION, USAGE, BILLING, SUBSCRIPTION, PLAN,
    ROLE, PERMISSION, GROUP, TEAM, PROJECT, TASK, COMMENT, ATTACHMENT,
    OTHER
}
